const EQUIPMENT_CATALOG = [
  // Primary weapons included in base game price
  {
    key: "weapon_g36",
    title: "G36",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/g36.png",
    price: 0,
    defaultStock: 3,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_ar",
    title: "AR",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/ar.png",
    price: 0,
    defaultStock: null,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_m4",
    title: "M4",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/m4.png",
    price: 0,
    defaultStock: null,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_ak47",
    title: "AK-47",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/ak47.png",
    price: 0,
    defaultStock: null,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_aks74u",
    title: "AKC-74Y",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/akc74y.png",
    price: 0,
    defaultStock: null,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_mp5k",
    title: "MP-5K",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/mp5k.png",
    price: 0,
    defaultStock: 1,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_mp5",
    title: "MP-5",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/mp5.png",
    price: 0,
    defaultStock: 1,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_ak74",
    title: "AK-74",
    category: "primary_weapon",
    description: "Стандартний привід (входить у базову вартість).",
    imageUrl: "/equipment/ak74.png",
    price: 0,
    defaultStock: null,
    maxPerPlayer: 1,
  },

  // Premium / special loadouts
  {
    key: "weapon_ar_mg",
    title: "AR-кулемет",
    category: "premium_weapon",
    description: "Преміум варіант. Доплата до участі: 700 грн.",
    imageUrl: "/equipment/ar-mg.png",
    price: 700,
    defaultStock: null,
    maxPerPlayer: 1,
  },
  {
    key: "weapon_ar_full_mod",
    title: "AR + коліматор + глушник + стробоскоп + фонарь",
    category: "premium_weapon",
    description: "Преміум варіант. Доплата до участі: 700 грн.",
    imageUrl: "/equipment/ar-full.png",
    price: 700,
    defaultStock: null,
    maxPerPlayer: 1,
  },

  // Ammo / add-ons
  {
    key: "ammo_refill",
    title: "Поповнення магазину",
    category: "ammo",
    description: "Додаткове поповнення магазину.",
    imageUrl: "/equipment/balls-pack.png",
    price: 100,
    defaultStock: null,
    maxPerPlayer: 20,
  },
  {
    key: "grenade_cardboard",
    title: "Граната картонна",
    category: "consumable",
    description: "Картонна граната.",
    imageUrl: "/equipment/he-grenade.png",
    price: 50,
    defaultStock: null,
    maxPerPlayer: 20,
  },
  {
    key: "grenade_plastic",
    title: "Граната пластикова",
    category: "consumable",
    description: "Пластикова граната.",
    imageUrl: "/equipment/pl-he-grenade.png",
    price: 125,
    defaultStock: null,
    maxPerPlayer: 20,
  },
  {
    key: "smoke_cardboard",
    title: "Дим картонний",
    category: "consumable",
    description: "Картонний дим.",
    imageUrl: "/equipment/smoke-grenade.png",
    price: 170,
    defaultStock: null,
    maxPerPlayer: 20,
  },
  {
    key: "rpg_rental",
    title: "RPG (оренда)",
    category: "heavy",
    description: "Оренда RPG.",
    imageUrl: "/equipment/rocket-launcher.png",
    price: 200,
    defaultStock: 1,
    maxPerPlayer: 1,
  },
  {
    key: "rpg_shell",
    title: "ВОГ (снаряд до RPG)",
    category: "heavy",
    description: "Снаряд для RPG.",
    imageUrl: "/equipment/rpg-shell.png",
    price: 80,
    defaultStock: null,
    maxPerPlayer: 20,
  },
];

const EQUIPMENT_BY_KEY = Object.fromEntries(
  EQUIPMENT_CATALOG.map((item) => [item.key, item]),
);

module.exports = {
  EQUIPMENT_CATALOG,
  EQUIPMENT_BY_KEY,
};
